"""update db 3.0

Revision ID: 1cd84cac8b97
Revises: 23c342f9c691
Create Date: 2023-10-22 22:22:43.586658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd84cac8b97'
down_revision = '23c342f9c691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calgot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurusan', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calgot', schema=None) as batch_op:
        batch_op.drop_column('jurusan')

    # ### end Alembic commands ###
