"""update db 2.0

Revision ID: 23c342f9c691
Revises: ed05026f5be4
Create Date: 2023-10-21 21:10:34.593900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c342f9c691'
down_revision = 'ed05026f5be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calgot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alasan', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calgot', schema=None) as batch_op:
        batch_op.drop_column('alasan')

    # ### end Alembic commands ###
